[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = "0.8"
log = "0.4"
petgraph = "0.6"
serde = { version = "1.0", features = ["derive"] }
parking_lot = "0.12"
thiserror = "1.0"
uuid = { version = "1.3", features = ["v4"] }
cpal = "0.15"
